# Generated by Django 5.1.5 on 2025-01-30 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setting_conference_event_type_user_orcid_venue_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='conference',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='.')),
                ('name', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('organizers', models.CharField(max_length=1000)),
                ('capacity', models.IntegerField()),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop')], max_length=1000)),
                ('attendees', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue')),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='main.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
