# Generated by Django 5.1.5 on 2025-01-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_session_conference_remove_deadline_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='chairs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dietary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='disability',
            field=models.TextField(blank=True),
        ),
    ]
