# Generated by Django 5.1.5 on 2025-02-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_logo_alter_venue_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='room',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='session',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='short_name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='country',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='province',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity_abstract',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='long_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.FileField(upload_to='./media/abstract')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='main.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField()),
                ('answer', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
