# Generated by Django 5.1.5 on 2025-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_session_room_remove_session_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='is_abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deadline',
            name='is_registration',
            field=models.BooleanField(default=False),
        ),
    ]
