# Generated by Django 5.1.5 on 2025-02-02 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deadline_is_abstract_deadline_is_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(max_length=50),
        ),
    ]
