# Generated by Django 5.1.5 on 2025-02-02 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_admins_alter_user_email_alter_user_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.customquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
