# Generated by Django 5.1.5 on 2025-02-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customquestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='description',
        ),
    ]
