# Generated by Django 5.1 on 2025-03-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_deadline_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='customanswer',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customanswer',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customanswer',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='DefaultAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=1000)),
                ('nationality', models.IntegerField()),
                ('institute', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('disability', models.TextField()),
                ('dietary', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
