# Generated by Django 5.1 on 2025-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_customanswer_answer_customanswer_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultanswers',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='dietary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='disability',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
