# Generated by Django 5.1 on 2025-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_defaultanswers_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_info',
            field=models.URLField(blank=True),
        ),
    ]
