# Generated by Django 5.1 on 2025-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_link_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepts_abstract',
            field=models.BooleanField(default=False),
        ),
    ]
