# Generated by Django 5.1 on 2025-03-03 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_abstract_abstract_abstract_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
