# Generated by Django 5.1 on 2025-03-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_abstract_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orcid',
        ),
    ]
