# Generated by Django 5.1 on 2025-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_value_customanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customanswer',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
