# Generated by Django 5.1 on 2025-03-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_customanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speakers',
            new_name='Speaker',
        ),
    ]
