# Generated by Django 5.1 on 2025-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_speakers_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('invited', 'Invited'), ('contributed', 'Contributed'), ('short', 'Short'), ('poster', 'Poster')], default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='is_domestic',
            field=models.BooleanField(default=False),
        ),
    ]
