# Generated by Django 5.1 on 2025-03-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_event_venue_delete_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
    ]
