# Generated by Django 5.1 on 2025-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_event_description_remove_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abstract_deadline',
            field=models.DateField(blank=True, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, default=None, null=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
    ]
