# Generated by Django 5.1 on 2025-03-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='email_template_abstract_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_abstract_submission', to='main.emailtemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_template_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_registration', to='main.emailtemplate'),
        ),
    ]
