# Generated by Django 5.1 on 2025-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='type',
            field=models.CharField(choices=[('keynote', 'Keynote Talk'), ('invited', 'Invited Talk'), ('contributed', 'Contributed Talk'), ('short', 'Short Talk'), ('poster', 'Poster')], max_length=1000),
        ),
    ]
