# Generated by Django 5.1 on 2025-03-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_speaker_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviewers',
            new_name='Reviewer',
        ),
    ]
