# Generated by Django 5.1 on 2025-03-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_reviewers_reviewer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultAnswers',
            new_name='Attendee',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='event',
        ),
        migrations.AddField(
            model_name='abstract',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='main.attendee'),
        ),
        migrations.AddField(
            model_name='customanswer',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to='main.attendee'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='main.attendee'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewed_events', to='main.attendee'),
        ),
        migrations.DeleteModel(
            name='EmailContent',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
