# Generated by Django 5.1 on 2025-03-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_defaultanswers_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attendee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.attendee'),
        ),
    ]
