# Generated by Django 5.1 on 2025-03-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_abstractreview_reviewer_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='attendee',
        ),
        migrations.AddField(
            model_name='customquestion',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='main.event'),
        ),
    ]
