# Generated by Django 5.1 on 2025-03-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_customquestion_attendee_customquestion_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanswer',
            name='event',
        ),
    ]
