# Generated by Django 5.1 on 2025-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_customanswer_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractreview',
            name='score',
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
