# Generated by Django 5.1 on 2025-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_abstractreview_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_votes',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
