# Generated by Django 5.1 on 2025-03-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_event_max_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attendee')),
                ('voted_abstracts', models.ManyToManyField(related_name='votes', to='main.abstract')),
            ],
        ),
        migrations.DeleteModel(
            name='AbstractReview',
        ),
    ]
