# Generated by Django 5.1 on 2025-03-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_abstractvote_delete_abstractreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractvote',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
            preserve_default=False,
        ),
    ]
